
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloud-security-scanner
  description: Multi-cloud security posture scanning
  links:
    - url: https://github.com/shohrabniaz/cloud-security-scanner
      title: Repository
spec:
  type: service
  lifecycle: experimental
  owner: guests
